config/routes.rb
Rails.application.routes.draw do

  root 'pdf_readers#initiate'
  get 'pdf2excel' => 'pdf_readers#initiate'
  get 'pdf2excel_translate' => 'pdf_readers#translate_initiate'

  post '/transform' => "pdf_readers#transform"
  post '/translate' => "pdf_readers#translate"

  get 'download_pdf_excel' => "pdf_readers#download_excel"
  get '/download_pdf_excel_translate' => 'pdf_readers#download_excel_translate'  

  post '/find_bs_content' => "brightscope#find_bs_content"
  get 'download_bs_excel' => "brightscope#download_excel"
  get 'brightscope' => 'brightscope#initiate'

end

app/controllers/pdf_readers_controller.rb
class PdfReadersController < ApplicationController
	
	def initiate
	end

	def translate_initiate
	end

	def translate
		language = params[:language]
		pdf_file = params[:pdf_file]
		page_start = params[:page_start]
		page_end = params[:page_end]
		page_end = page_start if page_end.nil?
		pages = define_pages(page_start, page_end)

		wb_name = "PDF2EXCEL - Translate" + ".xls"
		workbook = WriteExcel.new(wb_name)
		pages.each do |page|
			file = Pdf2excel.new(pdf_file.path,page)
			# binding.pry
			worksheet = workbook.add_worksheet
			file.get_content
			file.set_col_position
			file.transform_content_translation(language)
			index = 0
			file.mod_content.each do |info|
				worksheet.write_row(index, 0, info)
			index += 1
			end
		end	
		workbook.close
		redirect_to :pdf2excel_translate, notice: "Success at #{Time.now.strftime("%m-%d-%y at %H:%M")}! #{view_context.link_to('Download Excel', download_pdf_excel_translate_path)}"
	end
	
	def transform
		pdf_file = params[:pdf_file]
		page_start = params[:page_start]
		page_end = params[:page_end]
		page_end = page_start if page_end.nil?
		pages = define_pages(page_start, page_end)
		wb_name = "PDF2EXCEL" + ".xls"
		workbook = WriteExcel.new(wb_name)
		pages.each do |page|
			file = Pdf2excel.new(pdf_file.path,page)
			worksheet = workbook.add_worksheet
			file.get_content
			file.set_col_position
			file.transform_content
			index = 0
			file.mod_content.each do |info|
				worksheet.write_row(index, 0, info)
			index += 1
			end
		end	
		workbook.close
		redirect_to :pdf2excel, notice: "Success at #{Time.now.strftime("%m-%d-%y at %H:%M")}! #{view_context.link_to('Download Excel', download_pdf_excel_path)}"
	end

	def download_excel
		require 'open-uri'
		file_path = "#{Rails.root}/PDF2EXCEL.xls"
		send_file file_path, :filename => "PDF2EXCEL.xls", :disposition => 'attachment'	
	end

	def download_excel_translate
		require 'open-uri'
		file_path = "#{Rails.root}/PDF2EXCEL - Translate.xls"
		send_file file_path, :filename => "PDF2EXCEL - Translate.xls", :disposition => 'attachment'	
	end

	private
	
	def pdf_reader_params
		params.require(:pdf_reader).permit(:file, :page, :full_content, :info_content, :mod_content, :y_precision, :col_position, :max)
	end

	def define_pages(page_start, page_end)
		# binding.pry
		pages = []
		for page in page_start..page_end
			pages << page.to_i
		end
		return pages
	end

end

app/helpers/pdf_readers_helper.rb
module PdfReadersHelper

  def language_choices
    [['Arabic','ar'],['Chinese Simplified','zh-CN'],['Chinese Traditional','zh-TW'],['Czech','cs'],['Danish','da'],['Dutch','nl'],['Finnish','fi'],['French','fr'],['German','de'],['Greek','el'],['Hebrew','iw'],['Hindi','hi'],['Hungarian','hu'],['Indonesian','id'],['Irish','ga'],['Italian','it'],['Japanese','ja'],['Korean','ko'],['Latvian','lv'],['Lithuanian','lt'],['Malay','ms'],['Norwegian','no'],['Persian','fa'],['Polish','pl'],['Portuguese','pt'],['Romanian','ro'],['Russian','ru'],['Spanish','es'],['Swedish','sv'],['Thai','th'],['Ukrainian','uk'],['Vietnamese','vi'],['Yiddish','yi']]
  end

end

app/views/pdf_readers/initiate.html.erb
<div class="container">
	<div class= "col-md-8 col-md-offset-2">
		<div class= "col-md-offset-4">
			<strong>
			PDF2Excel Reader 
			</strong>
		</div>
		<div class="flash">
			<%=sanitize(flash[:notice]) %>
		</div>	  	
		<br>
		<div class="form-group">
		<%= form_tag transform_path, multipart: true do %>
			<label> Upload File - PDF only </label> <%= file_field_tag :pdf_file %>
			<br>
			<div class ="row"> 
				<strong>The tool works best with pages with only financial informations (cash flows, balance sheet, income). </strong>
			</div>
	
			<br> 

			<label> Page Start </label> <%= number_field_tag :page_start, class: "form-control" %>
			<label> Page End </label> <%= number_field_tag :page_end, :class => "btn btn-default" %>

			<br> </br>
			
			<%= button_tag(type: "submit", class: "btn btn-primary", confirm: "Are there ONLY financials (no lengthy text) included in this pdf?") do %>
				Submit
			<% end %>
		<%end %>
		</div>
		<div class= "row">
			<strong style="color: #A70B32;">  
			The quality of PDF files are not standardized, please review the excel output closely before use.
			</strong>
		</div>	
	</div>

	<
</div>

app/views/pdf_readers/translate_initiate.html.erb
<div class="container">
  <div class= "col-md-8 col-md-offset-2">
    <div class= "col-md-offset-4">
      <strong>
      PDF2Excel Reader - Translation Services
      </strong>
    </div>
    <div class="flash">
      <%=sanitize(flash[:notice]) %>
    </div>      
    <br>
    <div class="form-group">
    <%= form_tag translate_path, multipart: true do %>
      <label> Upload File - PDF only </label> <%= file_field_tag :pdf_file %>
      <br>
      <div class ="row" style="color: #A70B32;"> 
        <strong>Do NOT use this tool to translate pages with many paragraphs of text. Do NOT be greedy with our quota. This tool is STRICTLY for foreign financials (income, balance sheets, and cash flow statements). </strong>
      </div>
      <br>
      <label> Language </label> <%= select_tag :language, options_for_select(language_choices), :class => "form-control" %>
      <br> 

      <label> Page Start </label> <%= number_field_tag :page_start, class: "form-control" %>
      <label> Page End </label> <%= number_field_tag :page_end, :class => "form-control" %>

      <br> </br>


      <%= button_tag(type: "submit", class: "btn btn-primary", confirm: 'Are you sure you need translation service?') do %>
        Submit
      <% end %>
    <%end %>
    </div>
    <div class= "row">
      <strong style="color: #A70B32;">  
      The quality of PDF files are not standardized, please review the excel output closely before use.
      </strong>
    </div>  
  </div>
</div>