config/routes.rb
Rails.application.routes.draw do

  root 'pdf_readers#initiate'
  get 'pdf2excel' => 'pdf_readers#initiate'
  get 'pdf2excel_translate' => 'pdf_readers#translate_initiate'

  post '/transform' => "pdf_readers#transform"
  post '/translate' => "pdf_readers#translate"

  get 'download_pdf_excel' => "pdf_readers#download_excel"
  get '/download_pdf_excel_translate' => 'pdf_readers#download_excel_translate'  

  post '/find_bs_content' => "brightscope#find_bs_content"
  get 'download_bs_excel' => "brightscope#download_excel"
  get 'brightscope' => 'brightscope#initiate'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivCo Internal Tools</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top " role="navigation">
    <div class="container-fluid" >
    	<div class="navbar-header page-scroll">
        <div class="navbar-brand custom" style="color:#F1ECDC">
    	    PrivCo Internal Tools
    	  </div>
      </div>
        <div class="collapse navbar-collapse ">
          <ul class="nav navbar-nav custom">
            <li class="active"> <%=link_to 'PDF2Excel', pdf2excel_path, class: "link" %> </li>
            <li class="active"> <%=link_to 'Translation Service', pdf2excel_translate_path, class: "link" %>  </li>
            <li class="active"> <%=link_to 'BrightScope', brightscope_path, class: "link" %>  </li>
          </ul>
        </div>


    </div> 
  </nav>


<%= yield %>

</body>
</html>